kind: pipeline
type: docker
name: formatAlertForPush

steps:
  - name: build
    image: node:10-alpine
    commands:
      - cd formatAlertForPush
      - npm install

---

kind: pipeline
type: docker
name: gtfsPoller

steps:
  - name: build
    image: node:10-alpine
    commands:
      - cd gtfsPoller
      - npm install
      - mkdir dist
      - mv node_modules dist
      - npm install --save-dev @babel/core @babel/cli
      - npx babel *.js --out-dir dist
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: poller.bounceme.net
      username: deploy
      key:
        from_secret: POLLER_SSH_KEY
      source: gtfsPoller/dist/*
      target: /home/ec2-user/tfnsw
      strip_components: 2
