#%RAML 1.0

title: TFNSW subscription type
version: 1.0

types:
  Subscription:
    type: object
    properties:
      type: 
        enum: [ route, trip, stop ]
      topic: string
      targetType:
        enum: [ email ]
      target: string
      id: string
      
  NewSubscription:
    type: object
    properties:
      type: 
        enum: [ route, trip, stop ]
      topic: string
      targetType:
        enum: [ email ]
      target: string
