#%RAML 1.0

title: TFNSW subscription management
version: 1.0
uses: 
  typelib: subscription-type.raml

/subscription:
  get:
    responses:
      200:
        body:
          application/json:
            type: [ typelib.Subscription ]
      401:
  post:
    body:
      application/json:
        type: typelib.NewSubscription
    responses:
      200:
        body:
          application/json:
            type:  typelib.Subscription 
      401:
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type:  typelib.Subscription 
        401:
        404:
    delete:
      responses:
        200:
        401:
        404:
    put:
      responses:
        200:
          body:
            application/json:
              type:  typelib.Subscription 
        401:
        404:
