pipeline {
  agent none
    parameters { 
      string(name: 'Environment', defaultValue: 'dev', description: 'target environment name')
    }


  stages {
    stage('build') {
      agent {
        docker {
          image 'node:10-alpine'
            args '-p 3000:3000'
        }
      }
      steps {
        sh 'cd formatAlertForPush'
        sh 'npm install'
      }
    }

  }
}
