pipeline {
  agent none
  parameters { 
    string(name: 'Environment', defaultValue: 'dev', description: 'target environment name')
  }

  agent {
    docker {
      image 'node:10-alpine'
        args '-p 3000:3000'
    }
  }

  stages {
    stage('build') {
      steps {
        sh 'npm install'
      }
    }

  }
}
